### ISSUE TITLE
Segfaults when opening some directories

### ISSUE THREAD

**Issue by 0xb8** [aperezdc/ngx-fancyindex#61]
Bug appeared in 1e438a6. Crashed with some big and small directories, but sadly I could not save exact directory listings. It also seems to crash with empty files present. Most likely cause is OOB in `ngx_sprintf(...sizes[j])`. 

Nginx version: `nginx/1.11.6`
Nginx config: 
```
...
http {
    fancyindex_exact_size off;
    fancyindex on;
    server {
        listen       80;
        server_name  localhost;
        location / {
            root   html;
            index  index.html index.htm;
        }
    }
}
```

Folder contents:
```
-rw-r--r-- 1 root root    0 Nov 25 00:07 test.txt
```

Crash info from systemd:
```
           PID: 6178 (nginx)
           UID: 33 (http)
           GID: 33 (http)
        Signal: 11 (SEGV)
    Executable: /usr/bin/nginx
    ...
                Stack trace of thread 6178:
                #0  0x00000000080e5921 ngx_vslprintf (nginx)
                #1  0x00000000080e5e48 ngx_sprintf (nginx)
                #2  0x000000000805eeef n/a (nginx)
                #3  0x00000000080cb996 ngx_http_core_content_phase (nginx)
                #4  0x00000000080c9189 ngx_http_core_run_phases (nginx)
                #5  0x00000000080dd6e7 ngx_http_process_request (nginx)
                #6  0x00000000080b9964 n/a (nginx)
                #7  0x00000000080a4926 n/a (nginx)
                #8  0x00000000080d4dce ngx_process_events_and_timers (nginx)
                #9  0x00000000080f334e n/a (nginx)
                #10 0x00000000080f1be7 ngx_spawn_process (nginx)
                #11 0x00000000080f2986 ngx_master_process_cycle (nginx)
                #12 0x0000000008054b86 main (nginx)
                #13 0x00000000b7267196 __libc_start_main (libc.so.6)
                #14 0x0000000008054d54 _start (nginx)
```

**Comment by aperezdc** [comment]
Sorry for taking a few days to comment. I'm just back from a long weekend, and right now is late in my timezone, but I will fix this tomorrow first thing in the morning. This is severe enough to grant a point release by itself.

**Comment by aperezdc** [comment]
Well, I have not been able of reproducing this...

@0xb8 Could you provide some more info to help me figure out why it's crashing for you but not here? The following would be useful to know:

* If you still have the core dumps around, running `coredumpctl gdb nginx`, entering the `backtrace` command, and pasting the output here would be most useful.
* The output of `nginx -V`.
* Linux distribution (Debian, Fedora, Arch...)
* Which architecture is your CPU? (From the long pointers, I'd guess 'x86_64')
* Is your build of Nginx done by you, or a package provided by your distribution?

**Comment by aperezdc** [comment]
FWIW, I have added a [test case in a branch](https://github.com/aperezdc/ngx-fancyindex/blob/bug61/t/bug61-empty-file-segfault.test) and it seems to [pass in all the CI configurations](https://travis-ci.org/aperezdc/ngx-fancyindex/builds/182044976).

**Comment by 0xb8** [comment]
I'm running 32-bit Arch with custom nginx build via PKGBUILD.
I also tried building with and without `-fstack-protector` (arch default is `strong`), made no difference.

```
$ nginx -V
nginx version: nginx/1.11.6
configure arguments: --prefix=/etc/nginx 
                     --conf-path=/etc/nginx/nginx.conf 
                     ...
                     --error-log-path=/var/log/nginx/error.log 
                     --user=http --group=http 
                     --with-ipv6 
                     --with-threads 
                     --with-file-aio
                     --with-pcre-jit 
                     --with-http_stub_status_module 
                     --with-http_gzip_static_module
                     --with-http_realip_module 
                     --with-http_addition_module 
                     --with-http_xslt_module 
                     --with-http_image_filter_module
                     --with-http_sub_module 
                     --with-http_flv_module
                     --with-http_mp4_module
                     --with-http_random_index_module 
                     --with-http_secure_link_module
                     --with-http_perl_module 
                     --with-http_degradation_module
                     --with-http_geoip_module 
                     --with-http_v2_module
                     --with-http_gunzip_module 
                     --with-http_auth_request_module 
                     --add-module=../ngx_fancyindex
```
Backtrace (debug build):
```
Core was generated by `nginx: worker process'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0805bf71 in ngx_vslprintf (buf=0x866ac74 "Y\354(\263\200\360\023\b\a", last=0xffffffff <error: Cannot access memory at address 0xffffffff>, fmt=0x8126738 "s", args=0xbfaca960 "\020h\022\bĩ\254\277")
    at src/core/ngx_string.c:256
256                         while (*p && buf < last) {
(gdb) bt
#0  0x0805bf71 in ngx_vslprintf (buf=0x866ac74 "Y\354(\263\200\360\023\b\a", last=0xffffffff <error: Cannot access memory at address 0xffffffff>, fmt=0x8126738 "s", args=0xbfaca960 "\020h\022\bĩ\254\277")
    at src/core/ngx_string.c:256
#1  0x0805bc72 in ngx_sprintf (buf=0x866ac72 "0 Y\354(\263\200\360\023\b\a", fmt=0x8126734 "%d %s") at src/core/ngx_string.c:111
#2  0x08112d1b in make_content_buf (r=0x8669aa8, pb=0xbfacaae0, alcf=0x8673270) at ../ngx_fancyindex/ngx_http_fancyindex_module.c:1000
#3  0x08112f60 in ngx_http_fancyindex_handler (r=0x8669aa8) at ../ngx_fancyindex/ngx_http_fancyindex_module.c:1060
#4  0x08090eda in ngx_http_core_content_phase (r=0x8669aa8, ph=0x86e6304) at src/http/ngx_http_core_module.c:1375
#5  0x0809004d in ngx_http_core_run_phases (r=0x8669aa8) at src/http/ngx_http_core_module.c:845
#6  0x0808ffdf in ngx_http_handler (r=0x8669aa8) at src/http/ngx_http_core_module.c:828
#7  0x0809be97 in ngx_http_process_request (r=0x8669aa8) at src/http/ngx_http_request.c:1914
#8  0x0809ae66 in ngx_http_process_request_headers (rev=0x87082b0) at src/http/ngx_http_request.c:1346
#9  0x0809a532 in ngx_http_process_request_line (rev=0x87082b0) at src/http/ngx_http_request.c:1026
#10 0x08099e03 in ngx_http_wait_request_handler (rev=0x87082b0) at src/http/ngx_http_request.c:503
#11 0x08089d8a in ngx_epoll_process_events (cycle=0x8664268, timer=60000, flags=1) at src/event/modules/ngx_epoll_module.c:907
#12 0x0807d182 in ngx_process_events_and_timers (cycle=0x8664268) at src/event/ngx_event.c:242
#13 0x08087c07 in ngx_worker_process_cycle (cycle=0x8664268, data=0x0) at src/os/unix/ngx_process_cycle.c:753
#14 0x08085416 in ngx_spawn_process (cycle=0x8664268, proc=0x8087b65 <ngx_worker_process_cycle>, data=0x0, name=0x81185f8 "worker process", respawn=-3) at src/os/unix/ngx_process.c:198
#15 0x0808717e in ngx_start_worker_processes (cycle=0x8664268, n=1, type=-3) at src/os/unix/ngx_process_cycle.c:358
#16 0x08086a1f in ngx_master_process_cycle (cycle=0x8664268) at src/os/unix/ngx_process_cycle.c:130
#17 0x08054804 in main (argc=3, argv=0xbfacb124) at src/core/nginx.c:367
(gdb)
```
Nginx debug log:
```
[debug] 31057#31057: *1 open index "/etc/nginx/html/index.html"
[debug] 31057#31057: *1 stat() "/etc/nginx/html/index.html" failed (2: No such file or directory)
[debug] 31057#31057: *1 http index check dir: "/etc/nginx/html"
[debug] 31057#31057: *1 open index "/etc/nginx/html/index.htm"
[debug] 31057#31057: *1 stat() "/etc/nginx/html/index.htm" failed (2: No such file or directory)
[debug] 31057#31057: *1 content phase: 15
[debug] 31057#31057: *1 http fancyindex: "/etc/nginx/html"
[debug] 31057#31057: *1 http fancyindex file: ".."
[debug] 31057#31057: *1 http fancyindex file: "test.txt"
[debug] 31057#31057: *1 http fancyindex file: "."
[debug] 31057#31057: *1 posix_memalign: 098C2AB0:4096 @16
[notice] 31056#31056: signal 17 (SIGCHLD) received
[alert] 31056#31056: worker process 31057 exited on signal 11 (core dumped)
```

**Comment by aperezdc** [comment]
@0xb8: Wow, that's really a good catch! Very good job pinpointing this. I see you posted PR #62 as well which fixes the issue. Let's merge it.

**Comment by aperezdc** [comment]
FWIW, probably it would be a good idea to try and setup Travis-CI to run 32-bit builds. Let's track that in #63 and close this issue.
